# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08d2bea2ae732c344781b91935ed0bad4b52054f0a15dd7ff31da0b0f5eb22f4582f1262d205b31e7bd7ab2d8e1c357f070e1df1ff2f61669978b52dfd3a5e60

test:
  secret_key_base: fbad80e2d0b9b5ac5017f90ae8ef77bc80dea6e8e65b9002810f2b133947f2f00b4589283492c55796b93db7c21aa62bfe0f8adabd3d1a5ca703386e86038897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
